/**
 * FDA RACC (Reference Amounts Customarily Consumed) Data
 * Based on 21 CFR 101.12 - Reference amounts customarily consumed per eating occasion
 * 
 * These values are used to determine appropriate serving sizes for nutrition labeling.
 * Last updated: December 2024
 * 
 * References:
 * - 21 CFR 101.12: https://www.ecfr.gov/current/title-21/chapter-I/subchapter-B/part-101/subpart-A/section-101.12
 * - FDA Serving Size Guidance: https://www.fda.gov/food/nutrition-education-resources-materials/serving-sizes-changed
 */

export interface RACCCategory {
    id: string;
    category: string;
    subcategory?: string;
    racc_amount: number;
    racc_unit: 'g' | 'mL' | 'pieces';
    label_statement: string;
    household_measure?: string;
    product_examples?: string[];
    notes?: string;
}

/**
 * FDA RACC Table 2 - Reference Amounts for the General Food Supply (4+ years)
 * Organized by food category as per 21 CFR 101.12(b)
 */
export const FDA_RACC_TABLE: RACCCategory[] = [
    // ===== BAKERY PRODUCTS =====
    {
        id: 'bakery-bagels',
        category: 'Bakery Products',
        subcategory: 'Bagels',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '1 bagel',
        household_measure: '1 bagel',
        product_examples: ['Plain bagels', 'Everything bagels', 'Mini bagels'],
    },
    {
        id: 'bakery-biscuits',
        category: 'Bakery Products',
        subcategory: 'Biscuits',
        racc_amount: 60,
        racc_unit: 'g',
        label_statement: '1 biscuit',
        household_measure: '1 biscuit (60g)',
        product_examples: ['Buttermilk biscuits', 'Flaky biscuits'],
    },
    {
        id: 'bakery-bread-sliced',
        category: 'Bakery Products',
        subcategory: 'Bread, sliced',
        racc_amount: 50,
        racc_unit: 'g',
        label_statement: '2 slices',
        household_measure: '2 slices',
        product_examples: ['White bread', 'Wheat bread', 'Sourdough'],
    },
    {
        id: 'bakery-bread-sticks',
        category: 'Bakery Products',
        subcategory: 'Bread sticks',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '30g',
        household_measure: 'about 2 sticks',
        product_examples: ['Soft breadsticks', 'Crispy breadsticks'],
    },
    {
        id: 'bakery-brownies',
        category: 'Bakery Products',
        subcategory: 'Brownies',
        racc_amount: 40,
        racc_unit: 'g',
        label_statement: '1 brownie',
        household_measure: '1 piece (40g)',
        product_examples: ['Chocolate brownies', 'Fudge brownies'],
    },
    {
        id: 'bakery-cake-heavy',
        category: 'Bakery Products',
        subcategory: 'Cake, heavy weight (density >0.8g/cc)',
        racc_amount: 80,
        racc_unit: 'g',
        label_statement: '1 piece',
        household_measure: '1 piece (80g)',
        product_examples: ['Cheesecake', 'Pound cake', 'Fruitcake'],
        notes: 'For cakes with density greater than 0.8g/cc',
    },
    {
        id: 'bakery-cake-medium',
        category: 'Bakery Products',
        subcategory: 'Cake, medium weight (density 0.35-0.8g/cc)',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 piece',
        household_measure: '1 piece (55g)',
        product_examples: ['Layer cakes', 'Cupcakes without frosting'],
        notes: 'For cakes with density 0.35-0.8g/cc',
    },
    {
        id: 'bakery-cake-light',
        category: 'Bakery Products',
        subcategory: 'Cake, light weight (density <0.35g/cc)',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '1 piece',
        household_measure: '1 piece (30g)',
        product_examples: ['Angel food cake', 'Chiffon cake'],
        notes: 'For cakes with density less than 0.35g/cc',
    },
    {
        id: 'bakery-cookies',
        category: 'Bakery Products',
        subcategory: 'Cookies',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '30g',
        household_measure: 'varies by size',
        product_examples: ['Chocolate chip cookies', 'Oatmeal cookies', 'Sugar cookies'],
    },
    {
        id: 'bakery-crackers',
        category: 'Bakery Products',
        subcategory: 'Crackers',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '30g',
        household_measure: 'varies by type',
        product_examples: ['Saltine crackers', 'Graham crackers', 'Cheese crackers'],
    },
    {
        id: 'bakery-croissants',
        category: 'Bakery Products',
        subcategory: 'Croissants',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 croissant',
        household_measure: '1 croissant',
        product_examples: ['Butter croissants', 'Chocolate croissants'],
    },
    {
        id: 'bakery-danish',
        category: 'Bakery Products',
        subcategory: 'Danish pastry',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 pastry',
        household_measure: '1 pastry (55g)',
        product_examples: ['Cheese danish', 'Fruit danish'],
    },
    {
        id: 'bakery-doughnuts',
        category: 'Bakery Products',
        subcategory: 'Doughnuts',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 doughnut',
        household_measure: '1 medium doughnut',
        product_examples: ['Glazed doughnuts', 'Cake doughnuts', 'Filled doughnuts'],
    },
    {
        id: 'bakery-english-muffins',
        category: 'Bakery Products',
        subcategory: 'English muffins',
        racc_amount: 57,
        racc_unit: 'g',
        label_statement: '1 muffin',
        household_measure: '1 muffin',
        product_examples: ['Plain English muffins', 'Whole wheat English muffins'],
    },
    {
        id: 'bakery-muffins',
        category: 'Bakery Products',
        subcategory: 'Muffins',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 muffin',
        household_measure: '1 medium muffin (55g)',
        product_examples: ['Blueberry muffins', 'Bran muffins', 'Corn muffins'],
    },
    {
        id: 'bakery-pancakes',
        category: 'Bakery Products',
        subcategory: 'Pancakes, waffles',
        racc_amount: 110,
        racc_unit: 'g',
        label_statement: '110g',
        household_measure: 'about 3 medium pancakes',
        product_examples: ['Buttermilk pancakes', 'Frozen waffles'],
    },
    {
        id: 'bakery-pies',
        category: 'Bakery Products',
        subcategory: 'Pies, fruit',
        racc_amount: 125,
        racc_unit: 'g',
        label_statement: '1 piece',
        household_measure: '1/8 of 8" pie',
        product_examples: ['Apple pie', 'Cherry pie', 'Pumpkin pie'],
    },
    {
        id: 'bakery-pizza-crust',
        category: 'Bakery Products',
        subcategory: 'Pizza crust',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '55g',
        household_measure: '1/6 of crust',
        product_examples: ['Thin crust', 'Traditional crust', 'Cauliflower crust'],
    },
    {
        id: 'bakery-rolls',
        category: 'Bakery Products',
        subcategory: 'Rolls, dinner type',
        racc_amount: 35,
        racc_unit: 'g',
        label_statement: '1 roll',
        household_measure: '1 roll',
        product_examples: ['Dinner rolls', 'Parker house rolls'],
    },
    {
        id: 'bakery-tortillas',
        category: 'Bakery Products',
        subcategory: 'Tortillas',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '1 tortilla',
        household_measure: '1 large tortilla',
        product_examples: ['Flour tortillas', 'Corn tortillas', 'Whole wheat tortillas'],
    },

    // ===== BEVERAGES =====
    {
        id: 'beverage-carbonated',
        category: 'Beverages',
        subcategory: 'Carbonated and noncarbonated beverages',
        racc_amount: 360,
        racc_unit: 'mL',
        label_statement: '12 fl oz',
        household_measure: '12 fl oz (360mL)',
        product_examples: ['Soda', 'Sparkling water', 'Energy drinks', 'Sports drinks'],
    },
    {
        id: 'beverage-coffee-tea',
        category: 'Beverages',
        subcategory: 'Coffee, tea (prepared)',
        racc_amount: 240,
        racc_unit: 'mL',
        label_statement: '1 cup',
        household_measure: '8 fl oz',
        product_examples: ['Brewed coffee', 'Brewed tea', 'Iced tea'],
    },
    {
        id: 'beverage-water',
        category: 'Beverages',
        subcategory: 'Water, bottled',
        racc_amount: 360,
        racc_unit: 'mL',
        label_statement: '12 fl oz',
        household_measure: '12 fl oz (360mL)',
        product_examples: ['Spring water', 'Purified water', 'Mineral water'],
    },

    // ===== CEREALS AND GRAINS =====
    {
        id: 'cereal-hot',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Hot cereals (dry)',
        racc_amount: 40,
        racc_unit: 'g',
        label_statement: '40g',
        household_measure: 'about 1/2 cup dry',
        product_examples: ['Oatmeal', 'Cream of wheat', 'Grits'],
    },
    {
        id: 'cereal-rte-less-dense',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Ready-to-eat cereals (less dense)',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '30g',
        household_measure: 'about 1 cup',
        product_examples: ['Puffed rice', 'Corn flakes', 'Cheerios'],
        notes: 'For cereals weighing less than 43g per cup',
    },
    {
        id: 'cereal-rte-dense',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Ready-to-eat cereals (dense)',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '55g',
        household_measure: 'about 1 cup',
        product_examples: ['Granola', 'Grape-Nuts', 'Muesli'],
        notes: 'For cereals weighing 43g or more per cup',
    },
    {
        id: 'grain-flour',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Flour',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '1/4 cup',
        household_measure: '1/4 cup (30g)',
        product_examples: ['All-purpose flour', 'Whole wheat flour', 'Bread flour'],
    },
    {
        id: 'grain-pasta-dry',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Pasta, dry',
        racc_amount: 56,
        racc_unit: 'g',
        label_statement: '2 oz dry',
        household_measure: '2 oz (56g) dry',
        product_examples: ['Spaghetti', 'Penne', 'Macaroni', 'Egg noodles'],
    },
    {
        id: 'grain-rice-dry',
        category: 'Cereals and Other Grain Products',
        subcategory: 'Rice, dry',
        racc_amount: 45,
        racc_unit: 'g',
        label_statement: '1/4 cup dry',
        household_measure: '1/4 cup dry',
        product_examples: ['White rice', 'Brown rice', 'Jasmine rice', 'Basmati rice'],
    },

    // ===== DAIRY PRODUCTS =====
    {
        id: 'dairy-milk',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Milk, all types',
        racc_amount: 240,
        racc_unit: 'mL',
        label_statement: '1 cup',
        household_measure: '1 cup (240mL)',
        product_examples: ['Whole milk', 'Skim milk', 'Almond milk', 'Oat milk'],
    },
    {
        id: 'dairy-yogurt',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Yogurt',
        racc_amount: 170,
        racc_unit: 'g',
        label_statement: '170g',
        household_measure: '3/4 cup',
        product_examples: ['Plain yogurt', 'Greek yogurt', 'Flavored yogurt'],
        notes: 'Updated from 225g per 2016 FDA rule',
    },
    {
        id: 'dairy-cheese-natural',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Cheese, natural',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '1 oz (28g)',
        product_examples: ['Cheddar', 'Swiss', 'Mozzarella', 'Parmesan'],
    },
    {
        id: 'dairy-cheese-cottage',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Cottage cheese',
        racc_amount: 110,
        racc_unit: 'g',
        label_statement: '1/2 cup',
        household_measure: '1/2 cup',
        product_examples: ['Regular cottage cheese', 'Low-fat cottage cheese'],
    },
    {
        id: 'dairy-cream-cheese',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Cream cheese, neufchatel',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '2 tbsp',
        product_examples: ['Regular cream cheese', 'Light cream cheese'],
    },
    {
        id: 'dairy-butter',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Butter, margarine',
        racc_amount: 14,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp (14g)',
        product_examples: ['Salted butter', 'Unsalted butter', 'Margarine'],
    },
    {
        id: 'dairy-cream',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Cream, half and half',
        racc_amount: 15,
        racc_unit: 'mL',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp',
        product_examples: ['Heavy cream', 'Light cream', 'Half and half'],
    },
    {
        id: 'dairy-sour-cream',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Sour cream',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Regular sour cream', 'Light sour cream'],
    },
    {
        id: 'dairy-ice-cream',
        category: 'Dairy Products and Substitutes',
        subcategory: 'Ice cream, frozen desserts',
        racc_amount: 2 / 3 * 150, // 2/3 cup = 100mL approx = 100g for ice cream
        racc_unit: 'g',
        label_statement: '2/3 cup',
        household_measure: '2/3 cup',
        product_examples: ['Ice cream', 'Frozen yogurt', 'Gelato', 'Sorbet'],
        notes: 'Updated from 1/2 cup per 2016 FDA rule',
    },

    // ===== DESSERTS =====
    {
        id: 'dessert-pudding',
        category: 'Desserts',
        subcategory: 'Puddings, custards',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1/2 cup',
        household_measure: '1/2 cup',
        product_examples: ['Chocolate pudding', 'Vanilla pudding', 'Flan'],
    },

    // ===== EGGS =====
    {
        id: 'eggs-whole',
        category: 'Egg and Egg Substitutes',
        subcategory: 'Eggs, whole',
        racc_amount: 50,
        racc_unit: 'g',
        label_statement: '1 egg',
        household_measure: '1 large egg',
        product_examples: ['Large eggs', 'Jumbo eggs'],
    },

    // ===== FATS AND OILS =====
    {
        id: 'fat-oil',
        category: 'Fats and Oils',
        subcategory: 'Oils',
        racc_amount: 14,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp (14g)',
        product_examples: ['Olive oil', 'Vegetable oil', 'Coconut oil', 'Canola oil'],
    },
    {
        id: 'fat-spray',
        category: 'Fats and Oils',
        subcategory: 'Cooking spray',
        racc_amount: 0.25,
        racc_unit: 'g',
        label_statement: '1/3 second spray',
        household_measure: 'about 1/3 second spray',
        product_examples: ['Cooking spray', 'Olive oil spray'],
    },
    {
        id: 'fat-mayonnaise',
        category: 'Fats and Oils',
        subcategory: 'Mayonnaise, dressings',
        racc_amount: 13,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp',
        product_examples: ['Mayonnaise', 'Miracle Whip'],
    },
    {
        id: 'fat-salad-dressing',
        category: 'Fats and Oils',
        subcategory: 'Salad dressing',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Ranch', 'Italian', 'Vinaigrette', 'Caesar'],
    },

    // ===== FISH AND SHELLFISH =====
    {
        id: 'fish-finfish',
        category: 'Fish, Shellfish, Game Meats',
        subcategory: 'Fish, finfish',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '3 oz',
        household_measure: '3 oz raw (about 2.25 oz cooked)',
        product_examples: ['Salmon', 'Tuna', 'Tilapia', 'Cod'],
    },
    {
        id: 'fish-shellfish',
        category: 'Fish, Shellfish, Game Meats',
        subcategory: 'Shellfish',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '3 oz',
        household_measure: '3 oz',
        product_examples: ['Shrimp', 'Crab', 'Lobster', 'Scallops'],
    },

    // ===== FRUITS AND FRUIT JUICES =====
    {
        id: 'fruit-fresh-whole',
        category: 'Fruits and Fruit Juices',
        subcategory: 'Fresh fruit, whole',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '140g',
        household_measure: '1 medium piece or 1 cup',
        product_examples: ['Apples', 'Bananas', 'Oranges', 'Berries'],
    },
    {
        id: 'fruit-canned',
        category: 'Fruits and Fruit Juices',
        subcategory: 'Canned, jarred fruit',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 cup',
        household_measure: '1 cup drained',
        product_examples: ['Canned peaches', 'Fruit cocktail', 'Mandarin oranges'],
    },
    {
        id: 'fruit-dried',
        category: 'Fruits and Fruit Juices',
        subcategory: 'Dried fruit',
        racc_amount: 40,
        racc_unit: 'g',
        label_statement: '40g',
        household_measure: 'about 1/4 cup',
        product_examples: ['Raisins', 'Dried cranberries', 'Dried apricots'],
    },
    {
        id: 'fruit-juice',
        category: 'Fruits and Fruit Juices',
        subcategory: 'Fruit juice',
        racc_amount: 240,
        racc_unit: 'mL',
        label_statement: '8 fl oz',
        household_measure: '1 cup (8 fl oz)',
        product_examples: ['Orange juice', 'Apple juice', 'Grape juice'],
    },

    // ===== LEGUMES =====
    {
        id: 'legumes-cooked',
        category: 'Legumes',
        subcategory: 'Beans, cooked',
        racc_amount: 130,
        racc_unit: 'g',
        label_statement: '1/2 cup',
        household_measure: '1/2 cup',
        product_examples: ['Black beans', 'Kidney beans', 'Chickpeas', 'Lentils'],
    },
    {
        id: 'legumes-hummus',
        category: 'Legumes',
        subcategory: 'Hummus, bean dip',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Hummus', 'Black bean dip', 'White bean dip'],
    },
    {
        id: 'legumes-tofu',
        category: 'Legumes',
        subcategory: 'Tofu, tempeh',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '3 oz',
        household_measure: '3 oz (about 1/4 block)',
        product_examples: ['Firm tofu', 'Silken tofu', 'Tempeh'],
    },

    // ===== MEAT AND POULTRY =====
    {
        id: 'meat-fresh',
        category: 'Meat, Poultry',
        subcategory: 'Meat, poultry (fresh)',
        racc_amount: 115,
        racc_unit: 'g',
        label_statement: '4 oz',
        household_measure: '4 oz raw (about 3 oz cooked)',
        product_examples: ['Beef', 'Chicken breast', 'Pork chops', 'Turkey'],
        notes: 'Updated from 85g per 2016 FDA rule',
    },
    {
        id: 'meat-processed',
        category: 'Meat, Poultry',
        subcategory: 'Processed meats (deli, hot dogs)',
        racc_amount: 55,
        racc_unit: 'g',
        label_statement: '2 oz',
        household_measure: '2 oz',
        product_examples: ['Deli ham', 'Turkey slices', 'Hot dogs', 'Bacon'],
    },
    {
        id: 'meat-jerky',
        category: 'Meat, Poultry',
        subcategory: 'Jerky',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '1 oz (28g)',
        product_examples: ['Beef jerky', 'Turkey jerky'],
    },

    // ===== MIXED DISHES =====
    {
        id: 'mixed-measurable',
        category: 'Mixed Dishes',
        subcategory: 'Mixed dishes (measurable)',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 cup',
        household_measure: '1 cup',
        product_examples: ['Macaroni and cheese', 'Stir fry', 'Casseroles'],
    },
    {
        id: 'mixed-pizza',
        category: 'Mixed Dishes',
        subcategory: 'Pizza',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 slice or 140g',
        household_measure: 'about 1/6 of 12" pizza',
        product_examples: ['Frozen pizza', 'Fresh pizza'],
    },
    {
        id: 'mixed-burrito',
        category: 'Mixed Dishes',
        subcategory: 'Burritos, tacos, wraps',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 item (140g)',
        household_measure: '1 burrito/wrap',
        product_examples: ['Burritos', 'Tacos', 'Wraps', 'Quesadillas'],
    },
    {
        id: 'mixed-sandwich',
        category: 'Mixed Dishes',
        subcategory: 'Sandwiches',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 sandwich',
        household_measure: '1 sandwich',
        product_examples: ['Frozen sandwiches', 'Pre-made sandwiches'],
    },
    {
        id: 'mixed-entree',
        category: 'Mixed Dishes',
        subcategory: 'Entrees with sauce',
        racc_amount: 280,
        racc_unit: 'g',
        label_statement: '1 bowl',
        household_measure: 'about 2 cups',
        product_examples: ['Frozen dinners', 'Pasta with sauce'],
    },

    // ===== NUTS AND SEEDS =====
    {
        id: 'nuts-shelled',
        category: 'Nuts and Seeds',
        subcategory: 'Nuts and seeds, shelled',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '1 oz (about 1/4 cup)',
        product_examples: ['Almonds', 'Cashews', 'Peanuts', 'Sunflower seeds'],
    },
    {
        id: 'nuts-butter',
        category: 'Nuts and Seeds',
        subcategory: 'Nut butter',
        racc_amount: 32,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Peanut butter', 'Almond butter', 'Sunflower seed butter'],
    },
    {
        id: 'nuts-coconut',
        category: 'Nuts and Seeds',
        subcategory: 'Coconut, dried',
        racc_amount: 15,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Shredded coconut', 'Coconut flakes'],
    },

    // ===== POTATOES =====
    {
        id: 'potato-fresh',
        category: 'Potatoes, Sweet Potatoes',
        subcategory: 'Fresh potatoes',
        racc_amount: 148,
        racc_unit: 'g',
        label_statement: '1 medium',
        household_measure: '1 medium potato',
        product_examples: ['Russet potatoes', 'Red potatoes', 'Sweet potatoes'],
    },
    {
        id: 'potato-fries',
        category: 'Potatoes, Sweet Potatoes',
        subcategory: 'French fries',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '3 oz',
        household_measure: 'about 10-15 fries',
        product_examples: ['Frozen French fries', 'Sweet potato fries'],
    },
    {
        id: 'potato-chips',
        category: 'Potatoes, Sweet Potatoes',
        subcategory: 'Potato chips',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '1 oz (about 15 chips)',
        product_examples: ['Regular chips', 'Kettle chips', 'Sweet potato chips'],
    },
    {
        id: 'potato-mashed',
        category: 'Potatoes, Sweet Potatoes',
        subcategory: 'Mashed potatoes, prepared',
        racc_amount: 140,
        racc_unit: 'g',
        label_statement: '1 cup',
        household_measure: '1 cup',
        product_examples: ['Instant mashed potatoes', 'Frozen mashed potatoes'],
    },

    // ===== SALADS =====
    {
        id: 'salad-no-dressing',
        category: 'Salads',
        subcategory: 'Salad, side type (no dressing)',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '1 cup',
        household_measure: '1 cup',
        product_examples: ['Garden salad', 'Mixed greens'],
    },

    // ===== SAUCES AND CONDIMENTS =====
    {
        id: 'sauce-major',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Sauce, major dish (tomato, pesto)',
        racc_amount: 125,
        racc_unit: 'g',
        label_statement: '1/2 cup',
        household_measure: '1/2 cup',
        product_examples: ['Marinara sauce', 'Alfredo sauce', 'Pesto'],
    },
    {
        id: 'sauce-minor',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Sauce, minor (soy, hot sauce)',
        racc_amount: 15,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp',
        product_examples: ['Soy sauce', 'Hot sauce', 'Worcestershire'],
    },
    {
        id: 'sauce-gravy',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Gravy',
        racc_amount: 60,
        racc_unit: 'g',
        label_statement: '1/4 cup',
        household_measure: '1/4 cup',
        product_examples: ['Brown gravy', 'Turkey gravy', 'Country gravy'],
    },
    {
        id: 'sauce-dip',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Dips (cheese, salsa)',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Salsa', 'Cheese dip', 'Guacamole', 'Queso'],
    },
    {
        id: 'sauce-ketchup',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Ketchup, BBQ sauce',
        racc_amount: 17,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp',
        product_examples: ['Ketchup', 'BBQ sauce', 'Steak sauce'],
    },
    {
        id: 'sauce-mustard',
        category: 'Sauces, Dips, Gravies, Condiments',
        subcategory: 'Mustard',
        racc_amount: 5,
        racc_unit: 'g',
        label_statement: '1 tsp',
        household_measure: '1 tsp',
        product_examples: ['Yellow mustard', 'Dijon mustard', 'Honey mustard'],
    },

    // ===== SNACKS =====
    {
        id: 'snack-chips',
        category: 'Snacks',
        subcategory: 'Chips, popcorn, snack mix',
        racc_amount: 28,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: '1 oz (28g)',
        product_examples: ['Tortilla chips', 'Pretzels', 'Popcorn', 'Snack mix'],
    },
    {
        id: 'snack-granola-bar',
        category: 'Snacks',
        subcategory: 'Granola bars, cereal bars',
        racc_amount: 40,
        racc_unit: 'g',
        label_statement: '1 bar',
        household_measure: '1 bar (40g)',
        product_examples: ['Granola bars', 'Cereal bars', 'Protein bars'],
    },
    {
        id: 'snack-trail-mix',
        category: 'Snacks',
        subcategory: 'Trail mix',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '30g',
        household_measure: 'about 3 tbsp',
        product_examples: ['Trail mix', 'Nut and fruit mix'],
    },

    // ===== SOUPS =====
    {
        id: 'soup-condensed',
        category: 'Soups',
        subcategory: 'Soup, condensed',
        racc_amount: 120,
        racc_unit: 'g',
        label_statement: '1/2 cup condensed',
        household_measure: '1/2 cup condensed (makes 1 cup)',
        product_examples: ['Condensed tomato soup', 'Cream of mushroom'],
    },
    {
        id: 'soup-ready',
        category: 'Soups',
        subcategory: 'Soup, ready to serve',
        racc_amount: 240,
        racc_unit: 'g',
        label_statement: '1 cup',
        household_measure: '1 cup',
        product_examples: ['Chicken noodle soup', 'Tomato soup', 'Minestrone'],
    },

    // ===== SUGARS AND SWEETS =====
    {
        id: 'sugar-granulated',
        category: 'Sugars and Sweets',
        subcategory: 'Sugar, granulated',
        racc_amount: 4,
        racc_unit: 'g',
        label_statement: '1 tsp',
        household_measure: '1 tsp (4g)',
        product_examples: ['White sugar', 'Brown sugar'],
    },
    {
        id: 'sweet-candy-hard',
        category: 'Sugars and Sweets',
        subcategory: 'Candy, hard',
        racc_amount: 15,
        racc_unit: 'g',
        label_statement: '15g',
        household_measure: 'about 3 pieces',
        product_examples: ['Hard candies', 'Lollipops', 'Candy canes'],
    },
    {
        id: 'sweet-candy-chocolate',
        category: 'Sugars and Sweets',
        subcategory: 'Chocolate, candy bars',
        racc_amount: 40,
        racc_unit: 'g',
        label_statement: '40g',
        household_measure: '1.4 oz',
        product_examples: ['Chocolate bars', 'Chocolate candy'],
    },
    {
        id: 'sweet-honey',
        category: 'Sugars and Sweets',
        subcategory: 'Honey, syrups, jams',
        racc_amount: 21,
        racc_unit: 'g',
        label_statement: '1 tbsp',
        household_measure: '1 tbsp',
        product_examples: ['Honey', 'Maple syrup', 'Jam', 'Jelly'],
    },
    {
        id: 'sweet-frosting',
        category: 'Sugars and Sweets',
        subcategory: 'Frosting',
        racc_amount: 33,
        racc_unit: 'g',
        label_statement: '2 tbsp',
        household_measure: '2 tbsp',
        product_examples: ['Cake frosting', 'Icing'],
    },

    // ===== VEGETABLES =====
    {
        id: 'vegetable-fresh',
        category: 'Vegetables',
        subcategory: 'Fresh vegetables',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '85g',
        household_measure: 'about 1 cup leafy, 1/2 cup other',
        product_examples: ['Carrots', 'Broccoli', 'Spinach', 'Tomatoes'],
    },
    {
        id: 'vegetable-canned',
        category: 'Vegetables',
        subcategory: 'Canned vegetables',
        racc_amount: 130,
        racc_unit: 'g',
        label_statement: '1/2 cup',
        household_measure: '1/2 cup drained',
        product_examples: ['Canned corn', 'Canned green beans', 'Canned peas'],
    },
    {
        id: 'vegetable-frozen',
        category: 'Vegetables',
        subcategory: 'Frozen vegetables',
        racc_amount: 85,
        racc_unit: 'g',
        label_statement: '85g',
        household_measure: 'about 3/4 cup',
        product_examples: ['Frozen peas', 'Frozen broccoli', 'Mixed vegetables'],
    },
    {
        id: 'vegetable-juice',
        category: 'Vegetables',
        subcategory: 'Vegetable juice',
        racc_amount: 240,
        racc_unit: 'mL',
        label_statement: '8 fl oz',
        household_measure: '1 cup (8 fl oz)',
        product_examples: ['Tomato juice', 'V8 juice', 'Carrot juice'],
    },
    {
        id: 'vegetable-pickled',
        category: 'Vegetables',
        subcategory: 'Pickles, relish',
        racc_amount: 30,
        racc_unit: 'g',
        label_statement: '1 oz',
        household_measure: 'about 1 pickle spear',
        product_examples: ['Dill pickles', 'Sweet pickles', 'Relish'],
    },
    {
        id: 'vegetable-olives',
        category: 'Vegetables',
        subcategory: 'Olives',
        racc_amount: 15,
        racc_unit: 'g',
        label_statement: '15g',
        household_measure: 'about 4 olives',
        product_examples: ['Black olives', 'Green olives', 'Kalamata olives'],
    },
];

/**
 * Get unique categories for dropdown selection
 */
export function getRACCCategories(): string[] {
    const categories = new Set(FDA_RACC_TABLE.map(r => r.category));
    return Array.from(categories).sort();
}

/**
 * Get RACC entries by category
 */
export function getRACCByCategory(category: string): RACCCategory[] {
    return FDA_RACC_TABLE.filter(r => r.category === category);
}

/**
 * Get RACC entry by ID
 */
export function getRACCById(id: string): RACCCategory | undefined {
    return FDA_RACC_TABLE.find(r => r.id === id);
}

/**
 * Search RACC entries by product example or category name
 */
export function searchRACC(query: string): RACCCategory[] {
    const q = query.toLowerCase();
    return FDA_RACC_TABLE.filter(r =>
        r.category.toLowerCase().includes(q) ||
        r.subcategory?.toLowerCase().includes(q) ||
        r.product_examples?.some(ex => ex.toLowerCase().includes(q))
    );
}

/**
 * Get all RACC entries as options for a dropdown
 */
export function getRACCOptions(): { value: string; label: string; category: string; racc: number; unit: string }[] {
    return FDA_RACC_TABLE.map(r => ({
        value: r.id,
        label: r.subcategory || r.category,
        category: r.category,
        racc: r.racc_amount,
        unit: r.racc_unit,
    }));
}
